services:
  - type: cronJob
    name: email-scraper-job
    env: python
    schedule: "0 0 * * *"  # Runs daily at midnight UTC
    buildCommand: pip install -r email-scraper/requirements.txt
    startCommand: cd email-scraper && python email_scraper.py
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REFRESH_TOKEN
        sync: false 