services:
  - type: worker
    name: email-scraper-worker
    env: python
    buildCommand: pip install -r email-scraper/requirements.txt
    startCommand: cd email-scraper && python email_scraper.py
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REFRESH_TOKEN
        sync: false 